### ISSUE TITLE
Input training data

### ISSUE THREAD

**Issue by Thomas-Frew** [UePG-21/facvae#2]
Good morning! 

I was wondering whether you training data was published anywhere for us to access, or if you could provide us with a sample? That would be amazing!

Thank you!

**Comment by UePG-21** [comment]
Sorry, the data contains private characteristics which I cannot provide. But you can find the detailed data structure in __init__.py.
________________________________
From: Thomas Frew ***@***.***>
Sent: Tuesday, September 12, 2023 8:01:22 PM
To: UePG-21/facvae ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [UePG-21/facvae] Input training data (Issue #2)


Good morning!

I was wondering whether you training data was published anywhere for us to access, or if you could provide us with a sample? That would be amazing!

Thank you!

**Comment by Thomas-Frew** [comment]
Would it be okay if you have me an example of a single row? I am happy to create my own dataset, but I find the structure in __init__.py difficult to understand.

**Comment by UePG-21** [comment]
Each row contains:

Date, StockID, feature1, ..., featureK

The first two are index, the others are columns.


________________________________

**Comment by Thomas-Frew** [comment]
Thank you!
